services:
  backend:
    container_name: bon-path-backend
    build: ./bon-path-backend
    volumes:
      - ./bon-path-backend:/backend
    ports:
      - "8080:8080"
    command: sh -c "npm run migrate:dev && npm run migrate:test && npm run dev"
    depends_on:
      - database
  database:
    container_name: bon-path-database
    image: postgres:latest
    environment:
      POSTGRES_USER: bonpath
      POSTGRES_PASSWORD: bonpath
      POSTGRES_DB: bonpath
    ports:
      - "5432:5432"